### ISSUE TITLE
プレビューページのURL貼り付けに失敗する

### ISSUE THREAD

**Issue by igrep** [haskell-jp/blog#78]
https://circleci.com/gh/haskell-jp/blog/157
https://circleci.com/gh/haskell-jp/blog/156
https://github.com/haskell-jp/blog/pull/74 で追加したはずの、「ビルド結果をプレビューするためのURLコメント機能」実行時に下記のエラーが発生した。

```
./artifact-preview.js
/home/ubuntu/blog/node_modules/circle-github-bot/dist/index.js:63
        throw new Error("Missing required environment variables:\n\n" + (missing.join('\n')) + "\n");
        ^

Error: Missing required environment variables:

GH_AUTH_TOKEN

    at Function.Bot.create (/home/ubuntu/blog/node_modules/circle-github-bot/dist/index.js:63:15)
    at Object.<anonymous> (/home/ubuntu/blog/artifact-preview.js:5:42)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Function.Module.runMain (module.js:442:10)
    at startup (node.js:136:18)
    at node.js:966:3

./artifact-preview.js returned exit code 1

Action failed: ./artifact-preview.js
```

なんで送ったPull requestではうまくいってたのにマージした途端うまくいったかは不明。。。

**Comment by igrep** [comment]
https://circleci.com/docs/1.0/environment-variables/#setting-environment-variables-for-all-commands-without-adding-them-to-git
曰く、

> It’s important to note that environment variables configured through the UI are exported during the machine section of the build. This means you cannot read UI environment variables during the `machine: pre`

らしい。これが関係している？

**Comment by igrep** [comment]
と、思ったけど関係なさそう。forum行きかなこりゃ。。。 😞

**Comment by igrep** [comment]
原因わかった 💡 

> Suppressing export of environment variables GITHUB_TOKEN, GH_AUTH_TOKEN fork PR builds

こんなメッセージがログに出てた 😅

**Comment by igrep** [comment]
@fumieval さん、もしよければ下記のいずれかの対策をやっていただきたく 🙇 

A. とりあえずのワークアラウンドとして `GH_AUTH_TOKEN` が未定義の場合は `./artifact-preview.js` では何もしない
B. Herokuかどこかに、Pull requestのIDを受け取ったらプレビューページのURLをコメントする、専用のアプリを作る

**Comment by igrep** [comment]
一旦クローズします。
